/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using MyGrainExchange.Api.Client;
using MyGrainExchange.Api.Model;

namespace MyGrainExchange.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthenticationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Revoke an access or refresh token
        /// </summary>
        /// <remarks>
        /// Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <returns>OauthRevokePost200Response</returns>
        OauthRevokePost200Response OauthRevokePost(string token, string? tokenTypeHint = default);

        /// <summary>
        /// Revoke an access or refresh token
        /// </summary>
        /// <remarks>
        /// Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <returns>ApiResponse of OauthRevokePost200Response</returns>
        ApiResponse<OauthRevokePost200Response> OauthRevokePostWithHttpInfo(string token, string? tokenTypeHint = default);
        /// <summary>
        /// Issue or refresh an access token
        /// </summary>
        /// <remarks>
        /// Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <returns>OauthTokenPost200Response</returns>
        OauthTokenPost200Response OauthTokenPost(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default);

        /// <summary>
        /// Issue or refresh an access token
        /// </summary>
        /// <remarks>
        /// Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <returns>ApiResponse of OauthTokenPost200Response</returns>
        ApiResponse<OauthTokenPost200Response> OauthTokenPostWithHttpInfo(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthenticationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Revoke an access or refresh token
        /// </summary>
        /// <remarks>
        /// Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OauthRevokePost200Response</returns>
        System.Threading.Tasks.Task<OauthRevokePost200Response> OauthRevokePostAsync(string token, string? tokenTypeHint = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revoke an access or refresh token
        /// </summary>
        /// <remarks>
        /// Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OauthRevokePost200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<OauthRevokePost200Response>> OauthRevokePostWithHttpInfoAsync(string token, string? tokenTypeHint = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Issue or refresh an access token
        /// </summary>
        /// <remarks>
        /// Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OauthTokenPost200Response</returns>
        System.Threading.Tasks.Task<OauthTokenPost200Response> OauthTokenPostAsync(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Issue or refresh an access token
        /// </summary>
        /// <remarks>
        /// Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </remarks>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OauthTokenPost200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<OauthTokenPost200Response>> OauthTokenPostWithHttpInfoAsync(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuthenticationApi : IAuthenticationApiSync, IAuthenticationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuthenticationApi : IDisposable, IAuthenticationApi
    {
        private MyGrainExchange.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AuthenticationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AuthenticationApi(string basePath)
        {
            this.Configuration = MyGrainExchange.Api.Client.Configuration.MergeConfigurations(
                MyGrainExchange.Api.Client.GlobalConfiguration.Instance,
                new MyGrainExchange.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new MyGrainExchange.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = MyGrainExchange.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AuthenticationApi(MyGrainExchange.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MyGrainExchange.Api.Client.Configuration.MergeConfigurations(
                MyGrainExchange.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new MyGrainExchange.Api.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = MyGrainExchange.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AuthenticationApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AuthenticationApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = MyGrainExchange.Api.Client.Configuration.MergeConfigurations(
                MyGrainExchange.Api.Client.GlobalConfiguration.Instance,
                new MyGrainExchange.Api.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new MyGrainExchange.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = MyGrainExchange.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AuthenticationApi(HttpClient client, MyGrainExchange.Api.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = MyGrainExchange.Api.Client.Configuration.MergeConfigurations(
                MyGrainExchange.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new MyGrainExchange.Api.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = MyGrainExchange.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AuthenticationApi(MyGrainExchange.Api.Client.ISynchronousClient client, MyGrainExchange.Api.Client.IAsynchronousClient asyncClient, MyGrainExchange.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MyGrainExchange.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public MyGrainExchange.Api.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MyGrainExchange.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MyGrainExchange.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MyGrainExchange.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MyGrainExchange.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Revoke an access or refresh token Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <returns>OauthRevokePost200Response</returns>
        public OauthRevokePost200Response OauthRevokePost(string token, string? tokenTypeHint = default)
        {
            MyGrainExchange.Api.Client.ApiResponse<OauthRevokePost200Response> localVarResponse = OauthRevokePostWithHttpInfo(token, tokenTypeHint);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke an access or refresh token Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <returns>ApiResponse of OauthRevokePost200Response</returns>
        public MyGrainExchange.Api.Client.ApiResponse<OauthRevokePost200Response> OauthRevokePostWithHttpInfo(string token, string? tokenTypeHint = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'token' when calling AuthenticationApi->OauthRevokePost");

            MyGrainExchange.Api.Client.RequestOptions localVarRequestOptions = new MyGrainExchange.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("token", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(token)); // form parameter
            if (tokenTypeHint != null)
            {
                localVarRequestOptions.FormParameters.Add("token_type_hint", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(tokenTypeHint)); // form parameter
            }

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OauthRevokePost200Response>("/oauth/revoke", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OauthRevokePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revoke an access or refresh token Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OauthRevokePost200Response</returns>
        public async System.Threading.Tasks.Task<OauthRevokePost200Response> OauthRevokePostAsync(string token, string? tokenTypeHint = default, System.Threading.CancellationToken cancellationToken = default)
        {
            MyGrainExchange.Api.Client.ApiResponse<OauthRevokePost200Response> localVarResponse = await OauthRevokePostWithHttpInfoAsync(token, tokenTypeHint, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revoke an access or refresh token Invalidate a token early — for example on logout or when rotating credentials. Pass &#x60;token_type_hint&#x3D;refresh_token&#x60; to also revoke the refresh tokens associated with the access token, preventing further refreshes.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token">The token to revoke.</param>
        /// <param name="tokenTypeHint">Hint for which token type is being revoked. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OauthRevokePost200Response)</returns>
        public async System.Threading.Tasks.Task<MyGrainExchange.Api.Client.ApiResponse<OauthRevokePost200Response>> OauthRevokePostWithHttpInfoAsync(string token, string? tokenTypeHint = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'token' when calling AuthenticationApi->OauthRevokePost");


            MyGrainExchange.Api.Client.RequestOptions localVarRequestOptions = new MyGrainExchange.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("token", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(token)); // form parameter
            if (tokenTypeHint != null)
            {
                localVarRequestOptions.FormParameters.Add("token_type_hint", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(tokenTypeHint)); // form parameter
            }

            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<OauthRevokePost200Response>("/oauth/revoke", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OauthRevokePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Issue or refresh an access token Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <returns>OauthTokenPost200Response</returns>
        public OauthTokenPost200Response OauthTokenPost(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default)
        {
            MyGrainExchange.Api.Client.ApiResponse<OauthTokenPost200Response> localVarResponse = OauthTokenPostWithHttpInfo(grantType, clientId, clientSecret, refreshToken, code, redirectUri, codeVerifier, scope);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Issue or refresh an access token Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <returns>ApiResponse of OauthTokenPost200Response</returns>
        public MyGrainExchange.Api.Client.ApiResponse<OauthTokenPost200Response> OauthTokenPostWithHttpInfo(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default)
        {
            // verify the required parameter 'grantType' is set
            if (grantType == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'grantType' when calling AuthenticationApi->OauthTokenPost");

            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'clientId' when calling AuthenticationApi->OauthTokenPost");

            // verify the required parameter 'clientSecret' is set
            if (clientSecret == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'clientSecret' when calling AuthenticationApi->OauthTokenPost");

            MyGrainExchange.Api.Client.RequestOptions localVarRequestOptions = new MyGrainExchange.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("grant_type", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(grantType)); // form parameter
            localVarRequestOptions.FormParameters.Add("client_id", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(clientId)); // form parameter
            localVarRequestOptions.FormParameters.Add("client_secret", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(clientSecret)); // form parameter
            if (refreshToken != null)
            {
                localVarRequestOptions.FormParameters.Add("refresh_token", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(refreshToken)); // form parameter
            }
            if (code != null)
            {
                localVarRequestOptions.FormParameters.Add("code", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(code)); // form parameter
            }
            if (redirectUri != null)
            {
                localVarRequestOptions.FormParameters.Add("redirect_uri", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(redirectUri)); // form parameter
            }
            if (codeVerifier != null)
            {
                localVarRequestOptions.FormParameters.Add("code_verifier", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(codeVerifier)); // form parameter
            }
            if (scope != null)
            {
                localVarRequestOptions.FormParameters.Add("scope", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(scope)); // form parameter
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post<OauthTokenPost200Response>("/oauth/token", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OauthTokenPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Issue or refresh an access token Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OauthTokenPost200Response</returns>
        public async System.Threading.Tasks.Task<OauthTokenPost200Response> OauthTokenPostAsync(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default, System.Threading.CancellationToken cancellationToken = default)
        {
            MyGrainExchange.Api.Client.ApiResponse<OauthTokenPost200Response> localVarResponse = await OauthTokenPostWithHttpInfoAsync(grantType, clientId, clientSecret, refreshToken, code, redirectUri, codeVerifier, scope, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Issue or refresh an access token Exchange credentials for an access token. Use &#x60;grant_type&#x3D;authorization_code&#x60; to complete the Login with MGX flow, &#x60;grant_type&#x3D;client_credentials&#x60; for machine-to-machine read-only access, or &#x60;grant_type&#x3D;refresh_token&#x60; to obtain a new access token (and a rotated refresh token) before the current one expires. Access tokens live 15 days; refresh tokens live 30 days. This endpoint is unauthenticated — the client credentials are supplied in the body.
        /// </summary>
        /// <exception cref="MyGrainExchange.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="grantType">The OAuth2 grant type.</param>
        /// <param name="clientId"></param>
        /// <param name="clientSecret">Required for confidential clients.</param>
        /// <param name="refreshToken">Required when &#x60;grant_type&#x3D;refresh_token&#x60;. The refresh token returned by a previous token response. (optional)</param>
        /// <param name="code">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. The authorization code returned to your redirect URI. (optional)</param>
        /// <param name="redirectUri">Required when &#x60;grant_type&#x3D;authorization_code&#x60;. Must match the client&#39;s registered redirect URI. (optional)</param>
        /// <param name="codeVerifier">The PKCE code verifier matching the &#x60;code_challenge&#x60; sent to the authorize endpoint. (optional)</param>
        /// <param name="scope">Space-delimited list of scopes. For a refresh, may be a subset of the originally granted scopes. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OauthTokenPost200Response)</returns>
        public async System.Threading.Tasks.Task<MyGrainExchange.Api.Client.ApiResponse<OauthTokenPost200Response>> OauthTokenPostWithHttpInfoAsync(string grantType, string clientId, string clientSecret, string? refreshToken = default, string? code = default, string? redirectUri = default, string? codeVerifier = default, string? scope = default, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'grantType' is set
            if (grantType == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'grantType' when calling AuthenticationApi->OauthTokenPost");

            // verify the required parameter 'clientId' is set
            if (clientId == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'clientId' when calling AuthenticationApi->OauthTokenPost");

            // verify the required parameter 'clientSecret' is set
            if (clientSecret == null)
                throw new MyGrainExchange.Api.Client.ApiException(400, "Missing required parameter 'clientSecret' when calling AuthenticationApi->OauthTokenPost");


            MyGrainExchange.Api.Client.RequestOptions localVarRequestOptions = new MyGrainExchange.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = MyGrainExchange.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("grant_type", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(grantType)); // form parameter
            localVarRequestOptions.FormParameters.Add("client_id", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(clientId)); // form parameter
            localVarRequestOptions.FormParameters.Add("client_secret", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(clientSecret)); // form parameter
            if (refreshToken != null)
            {
                localVarRequestOptions.FormParameters.Add("refresh_token", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(refreshToken)); // form parameter
            }
            if (code != null)
            {
                localVarRequestOptions.FormParameters.Add("code", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(code)); // form parameter
            }
            if (redirectUri != null)
            {
                localVarRequestOptions.FormParameters.Add("redirect_uri", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(redirectUri)); // form parameter
            }
            if (codeVerifier != null)
            {
                localVarRequestOptions.FormParameters.Add("code_verifier", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(codeVerifier)); // form parameter
            }
            if (scope != null)
            {
                localVarRequestOptions.FormParameters.Add("scope", MyGrainExchange.Api.Client.ClientUtils.ParameterToString(scope)); // form parameter
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<OauthTokenPost200Response>("/oauth/token", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("OauthTokenPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
