# coding: utf-8

"""
    MGX Enterprise API

    Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mgx.models.inventory_filters import InventoryFilters

class TestInventoryFilters(unittest.TestCase):
    """InventoryFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InventoryFilters:
        """Test InventoryFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InventoryFilters`
        """
        model = InventoryFilters()
        if include_optional:
            return InventoryFilters(
                commodities = [
                    mgx.models.commodity.Commodity(
                        slug = 'wheat', 
                        name = 'Wheat', )
                    ],
                grades = [
                    ''
                    ],
                provinces = [
                    ''
                    ],
                crop_years = [
                    56
                    ]
            )
        else:
            return InventoryFilters(
        )
        """

    def testInventoryFilters(self):
        """Test InventoryFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
