# coding: utf-8

"""
    MGX Enterprise API

    Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mgx.models.cash_bid_envelope import CashBidEnvelope

class TestCashBidEnvelope(unittest.TestCase):
    """CashBidEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashBidEnvelope:
        """Test CashBidEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashBidEnvelope`
        """
        model = CashBidEnvelope()
        if include_optional:
            return CashBidEnvelope(
                data = mgx.models.cash_bid.CashBid(
                    id = 'cb_9Xa1', 
                    identifier = 'CB-001', 
                    commodity = null, 
                    price = null, 
                    quantity_mt = 1.337, 
                    delivery_location_id = 56, 
                    location = null, 
                    delivery = mgx.models.update_cash_bid_delivery.UpdateCashBid_delivery(
                        start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    is_active = True, 
                    expires_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
            )
        else:
            return CashBidEnvelope(
        )
        """

    def testCashBidEnvelope(self):
        """Test CashBidEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
