/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyGrainExchange.Api.Model;
using MyGrainExchange.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyGrainExchange.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Bid
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BidTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Bid
        //private Bid instance;

        public BidTests()
        {
            // TODO uncomment below to create an instance of Bid
            //instance = new Bid();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Bid
        /// </summary>
        [Fact]
        public void BidInstanceTest()
        {
            // TODO uncomment below to test "IsType" Bid
            //Assert.IsType<Bid>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }

        /// <summary>
        /// Test the property 'InventoryId'
        /// </summary>
        [Fact]
        public void InventoryIdTest()
        {
            // TODO unit test for the property 'InventoryId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Grades'
        /// </summary>
        [Fact]
        public void GradesTest()
        {
            // TODO unit test for the property 'Grades'
        }

        /// <summary>
        /// Test the property 'QuantityMt'
        /// </summary>
        [Fact]
        public void QuantityMtTest()
        {
            // TODO unit test for the property 'QuantityMt'
        }

        /// <summary>
        /// Test the property 'Delivery'
        /// </summary>
        [Fact]
        public void DeliveryTest()
        {
            // TODO unit test for the property 'Delivery'
        }

        /// <summary>
        /// Test the property 'SubjectToSampleApproval'
        /// </summary>
        [Fact]
        public void SubjectToSampleApprovalTest()
        {
            // TODO unit test for the property 'SubjectToSampleApproval'
        }

        /// <summary>
        /// Test the property 'FobFarm'
        /// </summary>
        [Fact]
        public void FobFarmTest()
        {
            // TODO unit test for the property 'FobFarm'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'Counterparty'
        /// </summary>
        [Fact]
        public void CounterpartyTest()
        {
            // TODO unit test for the property 'Counterparty'
        }
    }
}
