/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyGrainExchange.Api.Model;
using MyGrainExchange.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyGrainExchange.Api.Test.Model
{
    /// <summary>
    ///  Class for testing Money
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MoneyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Money
        //private Money instance;

        public MoneyTests()
        {
            // TODO uncomment below to create an instance of Money
            //instance = new Money();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Money
        /// </summary>
        [Fact]
        public void MoneyInstanceTest()
        {
            // TODO uncomment below to test "IsType" Money
            //Assert.IsType<Money>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

        /// <summary>
        /// Test the property 'Firm'
        /// </summary>
        [Fact]
        public void FirmTest()
        {
            // TODO unit test for the property 'Firm'
        }
    }
}
