/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyGrainExchange.Api.Model;
using MyGrainExchange.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyGrainExchange.Api.Test.Model
{
    /// <summary>
    ///  Class for testing StoreFarm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StoreFarmTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StoreFarm
        //private StoreFarm instance;

        public StoreFarmTests()
        {
            // TODO uncomment below to create an instance of StoreFarm
            //instance = new StoreFarm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StoreFarm
        /// </summary>
        [Fact]
        public void StoreFarmInstanceTest()
        {
            // TODO uncomment below to test "IsType" StoreFarm
            //Assert.IsType<StoreFarm>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'NearestCity'
        /// </summary>
        [Fact]
        public void NearestCityTest()
        {
            // TODO unit test for the property 'NearestCity'
        }

        /// <summary>
        /// Test the property 'NearestProvince'
        /// </summary>
        [Fact]
        public void NearestProvinceTest()
        {
            // TODO unit test for the property 'NearestProvince'
        }
    }
}
