/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyGrainExchange.Api.Model;
using MyGrainExchange.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyGrainExchange.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookEventType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookEventTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookEventType
        //private WebhookEventType instance;

        public WebhookEventTypeTests()
        {
            // TODO uncomment below to create an instance of WebhookEventType
            //instance = new WebhookEventType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookEventType
        /// </summary>
        [Fact]
        public void WebhookEventTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookEventType
            //Assert.IsType<WebhookEventType>(instance);
        }
    }
}
