/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyGrainExchange.Api.Model;
using MyGrainExchange.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyGrainExchange.Api.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookDelivery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookDeliveryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookDelivery
        //private WebhookDelivery instance;

        public WebhookDeliveryTests()
        {
            // TODO uncomment below to create an instance of WebhookDelivery
            //instance = new WebhookDelivery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookDelivery
        /// </summary>
        [Fact]
        public void WebhookDeliveryInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookDelivery
            //Assert.IsType<WebhookDelivery>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Fact]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }

        /// <summary>
        /// Test the property 'AttemptedAt'
        /// </summary>
        [Fact]
        public void AttemptedAtTest()
        {
            // TODO unit test for the property 'AttemptedAt'
        }
    }
}
