/*
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mygrainexchange.mgx.api;

import com.mygrainexchange.mgx.ApiCallback;
import com.mygrainexchange.mgx.ApiClient;
import com.mygrainexchange.mgx.ApiException;
import com.mygrainexchange.mgx.ApiResponse;
import com.mygrainexchange.mgx.Configuration;
import com.mygrainexchange.mgx.Pair;
import com.mygrainexchange.mgx.ProgressRequestBody;
import com.mygrainexchange.mgx.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;
import com.mygrainexchange.mgx.model.Error;
import com.mygrainexchange.mgx.model.InventoryEnvelope;
import com.mygrainexchange.mgx.model.InventoryFilters;
import com.mygrainexchange.mgx.model.InventoryPage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InventoryApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InventoryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InventoryApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for inventoryFilters
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Available filter facets </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryFiltersCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/inventory/filters";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inventoryFiltersValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return inventoryFiltersCall(_callback);

    }

    /**
     * Facet metadata for filters
     * Returns the distinct commodities, grades, provinces, and crop years currently available.
     * @return InventoryFilters
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Available filter facets </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public InventoryFilters inventoryFilters() throws ApiException {
        ApiResponse<InventoryFilters> localVarResp = inventoryFiltersWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Facet metadata for filters
     * Returns the distinct commodities, grades, provinces, and crop years currently available.
     * @return ApiResponse&lt;InventoryFilters&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Available filter facets </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InventoryFilters> inventoryFiltersWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = inventoryFiltersValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<InventoryFilters>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Facet metadata for filters (asynchronously)
     * Returns the distinct commodities, grades, provinces, and crop years currently available.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Available filter facets </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryFiltersAsync(final ApiCallback<InventoryFilters> _callback) throws ApiException {

        okhttp3.Call localVarCall = inventoryFiltersValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<InventoryFilters>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inventoryGet
     * @param id Public inventory id, e.g. inv_3Kd9aZ. (required)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Inventory resource </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryGetCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String units, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/inventory/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (units != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("units", units));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inventoryGetValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String units, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling inventoryGet(Async)");
        }

        return inventoryGetCall(id, units, _callback);

    }

    /**
     * Get one anonymized listing
     * 
     * @param id Public inventory id, e.g. inv_3Kd9aZ. (required)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @return InventoryEnvelope
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Inventory resource </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
     </table>
     */
    public InventoryEnvelope inventoryGet(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String units) throws ApiException {
        ApiResponse<InventoryEnvelope> localVarResp = inventoryGetWithHttpInfo(id, units);
        return localVarResp.getData();
    }

    /**
     * Get one anonymized listing
     * 
     * @param id Public inventory id, e.g. inv_3Kd9aZ. (required)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @return ApiResponse&lt;InventoryEnvelope&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Inventory resource </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InventoryEnvelope> inventoryGetWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String units) throws ApiException {
        okhttp3.Call localVarCall = inventoryGetValidateBeforeCall(id, units, null);
        Type localVarReturnType = new TypeToken<InventoryEnvelope>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get one anonymized listing (asynchronously)
     * 
     * @param id Public inventory id, e.g. inv_3Kd9aZ. (required)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Inventory resource </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryGetAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String units, final ApiCallback<InventoryEnvelope> _callback) throws ApiException {

        okhttp3.Call localVarCall = inventoryGetValidateBeforeCall(id, units, _callback);
        Type localVarReturnType = new TypeToken<InventoryEnvelope>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for inventoryList
     * @param commodity Commodity slug(s), comma-separated, e.g. wheat,canola. (optional)
     * @param grade Grade code, e.g. 1CWRS. (optional)
     * @param minQuantity Minimum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param maxQuantity Maximum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param province Coarse location filter, e.g. SK, AB. (optional)
     * @param near lat,lng,radius_km — radius search against coarse city centroids. (optional)
     * @param cropYear  (optional)
     * @param isOrganic  (optional)
     * @param minProtein  (optional)
     * @param sort  (optional)
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Paging object of inventory </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryListCall(@javax.annotation.Nullable String commodity, @javax.annotation.Nullable String grade, @javax.annotation.Nullable BigDecimal minQuantity, @javax.annotation.Nullable BigDecimal maxQuantity, @javax.annotation.Nullable String province, @javax.annotation.Nullable String near, @javax.annotation.Nullable Integer cropYear, @javax.annotation.Nullable Boolean isOrganic, @javax.annotation.Nullable BigDecimal minProtein, @javax.annotation.Nullable String sort, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String units, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/inventory";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (commodity != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("commodity", commodity));
        }

        if (grade != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("grade", grade));
        }

        if (minQuantity != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_quantity", minQuantity));
        }

        if (maxQuantity != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_quantity", maxQuantity));
        }

        if (province != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("province", province));
        }

        if (near != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("near", near));
        }

        if (cropYear != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("crop_year", cropYear));
        }

        if (isOrganic != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("is_organic", isOrganic));
        }

        if (minProtein != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_protein", minProtein));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (units != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("units", units));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call inventoryListValidateBeforeCall(@javax.annotation.Nullable String commodity, @javax.annotation.Nullable String grade, @javax.annotation.Nullable BigDecimal minQuantity, @javax.annotation.Nullable BigDecimal maxQuantity, @javax.annotation.Nullable String province, @javax.annotation.Nullable String near, @javax.annotation.Nullable Integer cropYear, @javax.annotation.Nullable Boolean isOrganic, @javax.annotation.Nullable BigDecimal minProtein, @javax.annotation.Nullable String sort, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String units, final ApiCallback _callback) throws ApiException {
        return inventoryListCall(commodity, grade, minQuantity, maxQuantity, province, near, cropYear, isOrganic, minProtein, sort, limit, offset, units, _callback);

    }

    /**
     * Browse &amp; filter anonymized inventory
     * Returns a paged, anonymized list of grain listings. Seller identity, farm name, and exact coordinates are never included.
     * @param commodity Commodity slug(s), comma-separated, e.g. wheat,canola. (optional)
     * @param grade Grade code, e.g. 1CWRS. (optional)
     * @param minQuantity Minimum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param maxQuantity Maximum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param province Coarse location filter, e.g. SK, AB. (optional)
     * @param near lat,lng,radius_km — radius search against coarse city centroids. (optional)
     * @param cropYear  (optional)
     * @param isOrganic  (optional)
     * @param minProtein  (optional)
     * @param sort  (optional)
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @return InventoryPage
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Paging object of inventory </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public InventoryPage inventoryList(@javax.annotation.Nullable String commodity, @javax.annotation.Nullable String grade, @javax.annotation.Nullable BigDecimal minQuantity, @javax.annotation.Nullable BigDecimal maxQuantity, @javax.annotation.Nullable String province, @javax.annotation.Nullable String near, @javax.annotation.Nullable Integer cropYear, @javax.annotation.Nullable Boolean isOrganic, @javax.annotation.Nullable BigDecimal minProtein, @javax.annotation.Nullable String sort, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String units) throws ApiException {
        ApiResponse<InventoryPage> localVarResp = inventoryListWithHttpInfo(commodity, grade, minQuantity, maxQuantity, province, near, cropYear, isOrganic, minProtein, sort, limit, offset, units);
        return localVarResp.getData();
    }

    /**
     * Browse &amp; filter anonymized inventory
     * Returns a paged, anonymized list of grain listings. Seller identity, farm name, and exact coordinates are never included.
     * @param commodity Commodity slug(s), comma-separated, e.g. wheat,canola. (optional)
     * @param grade Grade code, e.g. 1CWRS. (optional)
     * @param minQuantity Minimum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param maxQuantity Maximum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param province Coarse location filter, e.g. SK, AB. (optional)
     * @param near lat,lng,radius_km — radius search against coarse city centroids. (optional)
     * @param cropYear  (optional)
     * @param isOrganic  (optional)
     * @param minProtein  (optional)
     * @param sort  (optional)
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @return ApiResponse&lt;InventoryPage&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Paging object of inventory </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<InventoryPage> inventoryListWithHttpInfo(@javax.annotation.Nullable String commodity, @javax.annotation.Nullable String grade, @javax.annotation.Nullable BigDecimal minQuantity, @javax.annotation.Nullable BigDecimal maxQuantity, @javax.annotation.Nullable String province, @javax.annotation.Nullable String near, @javax.annotation.Nullable Integer cropYear, @javax.annotation.Nullable Boolean isOrganic, @javax.annotation.Nullable BigDecimal minProtein, @javax.annotation.Nullable String sort, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String units) throws ApiException {
        okhttp3.Call localVarCall = inventoryListValidateBeforeCall(commodity, grade, minQuantity, maxQuantity, province, near, cropYear, isOrganic, minProtein, sort, limit, offset, units, null);
        Type localVarReturnType = new TypeToken<InventoryPage>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Browse &amp; filter anonymized inventory (asynchronously)
     * Returns a paged, anonymized list of grain listings. Seller identity, farm name, and exact coordinates are never included.
     * @param commodity Commodity slug(s), comma-separated, e.g. wheat,canola. (optional)
     * @param grade Grade code, e.g. 1CWRS. (optional)
     * @param minQuantity Minimum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param maxQuantity Maximum tonnes (MT). Interpreted in &#x60;?units&#x3D;&#x60; (default MT). (optional)
     * @param province Coarse location filter, e.g. SK, AB. (optional)
     * @param near lat,lng,radius_km — radius search against coarse city centroids. (optional)
     * @param cropYear  (optional)
     * @param isOrganic  (optional)
     * @param minProtein  (optional)
     * @param sort  (optional)
     * @param limit  (optional, default to 20)
     * @param offset  (optional, default to 0)
     * @param units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Paging object of inventory </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing or invalid token </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Token lacks the required scope or eligibility </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call inventoryListAsync(@javax.annotation.Nullable String commodity, @javax.annotation.Nullable String grade, @javax.annotation.Nullable BigDecimal minQuantity, @javax.annotation.Nullable BigDecimal maxQuantity, @javax.annotation.Nullable String province, @javax.annotation.Nullable String near, @javax.annotation.Nullable Integer cropYear, @javax.annotation.Nullable Boolean isOrganic, @javax.annotation.Nullable BigDecimal minProtein, @javax.annotation.Nullable String sort, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String units, final ApiCallback<InventoryPage> _callback) throws ApiException {

        okhttp3.Call localVarCall = inventoryListValidateBeforeCall(commodity, grade, minQuantity, maxQuantity, province, near, cropYear, isOrganic, minProtein, sort, limit, offset, units, _callback);
        Type localVarReturnType = new TypeToken<InventoryPage>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
