/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorErrorErrorsInner } from './ErrorErrorErrorsInner';
import {
    ErrorErrorErrorsInnerFromJSON,
    ErrorErrorErrorsInnerFromJSONTyped,
    ErrorErrorErrorsInnerToJSON,
    ErrorErrorErrorsInnerToJSONTyped,
} from './ErrorErrorErrorsInner';

/**
 * 
 * @export
 * @interface ErrorError
 */
export interface ErrorError {
    /**
     * 
     * @type {number}
     * @memberof ErrorError
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorError
     */
    message: string;
    /**
     * 
     * @type {Array<ErrorErrorErrorsInner>}
     * @memberof ErrorError
     */
    errors?: Array<ErrorErrorErrorsInner>;
}

/**
 * Check if a given object implements the ErrorError interface.
 */
export function instanceOfErrorError(value: object): value is ErrorError {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorErrorFromJSON(json: any): ErrorError {
    return ErrorErrorFromJSONTyped(json, false);
}

export function ErrorErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorError {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ErrorErrorErrorsInnerFromJSON)),
    };
}

export function ErrorErrorToJSON(json: any): ErrorError {
    return ErrorErrorToJSONTyped(json, false);
}

export function ErrorErrorToJSONTyped(value?: ErrorError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ErrorErrorErrorsInnerToJSON)),
    };
}

