/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Inventory } from './Inventory';
import {
    InventoryFromJSON,
    InventoryFromJSONTyped,
    InventoryToJSON,
    InventoryToJSONTyped,
} from './Inventory';

/**
 * 
 * @export
 * @interface InventoryPage
 */
export interface InventoryPage {
    /**
     * 
     * @type {number}
     * @memberof InventoryPage
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryPage
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryPage
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryPage
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryPage
     */
    previous?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryPage
     */
    href?: string;
    /**
     * 
     * @type {Array<Inventory>}
     * @memberof InventoryPage
     */
    items?: Array<Inventory>;
}

/**
 * Check if a given object implements the InventoryPage interface.
 */
export function instanceOfInventoryPage(value: object): value is InventoryPage {
    return true;
}

export function InventoryPageFromJSON(json: any): InventoryPage {
    return InventoryPageFromJSONTyped(json, false);
}

export function InventoryPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryPage {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'href': json['href'] == null ? undefined : json['href'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(InventoryFromJSON)),
    };
}

export function InventoryPageToJSON(json: any): InventoryPage {
    return InventoryPageToJSONTyped(json, false);
}

export function InventoryPageToJSONTyped(value?: InventoryPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'next': value['next'],
        'previous': value['previous'],
        'href': value['href'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(InventoryToJSON)),
    };
}

