/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceBidBidsInner
 */
export interface PlaceBidBidsInner {
    /**
     * 
     * @type {string}
     * @memberof PlaceBidBidsInner
     */
    grade: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceBidBidsInner
     */
    price: number;
}

/**
 * Check if a given object implements the PlaceBidBidsInner interface.
 */
export function instanceOfPlaceBidBidsInner(value: object): value is PlaceBidBidsInner {
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PlaceBidBidsInnerFromJSON(json: any): PlaceBidBidsInner {
    return PlaceBidBidsInnerFromJSONTyped(json, false);
}

export function PlaceBidBidsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceBidBidsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'grade': json['grade'],
        'price': json['price'],
    };
}

export function PlaceBidBidsInnerToJSON(json: any): PlaceBidBidsInner {
    return PlaceBidBidsInnerToJSONTyped(json, false);
}

export function PlaceBidBidsInnerToJSONTyped(value?: PlaceBidBidsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grade': value['grade'],
        'price': value['price'],
    };
}

