/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Non-identifying seller quality claims. All fields are optional.
 * @export
 * @interface Quality
 */
export interface Quality {
    /**
     * 
     * @type {number}
     * @memberof Quality
     */
    protein?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Quality
     */
    moisture?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Quality
     */
    testWeight?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Quality
     */
    dockage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Quality
     */
    fallingNumber?: number | null;
}

/**
 * Check if a given object implements the Quality interface.
 */
export function instanceOfQuality(value: object): value is Quality {
    return true;
}

export function QualityFromJSON(json: any): Quality {
    return QualityFromJSONTyped(json, false);
}

export function QualityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quality {
    if (json == null) {
        return json;
    }
    return {
        
        'protein': json['protein'] == null ? undefined : json['protein'],
        'moisture': json['moisture'] == null ? undefined : json['moisture'],
        'testWeight': json['test_weight'] == null ? undefined : json['test_weight'],
        'dockage': json['dockage'] == null ? undefined : json['dockage'],
        'fallingNumber': json['falling_number'] == null ? undefined : json['falling_number'],
    };
}

export function QualityToJSON(json: any): Quality {
    return QualityToJSONTyped(json, false);
}

export function QualityToJSONTyped(value?: Quality | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protein': value['protein'],
        'moisture': value['moisture'],
        'test_weight': value['testWeight'],
        'dockage': value['dockage'],
        'falling_number': value['fallingNumber'],
    };
}

