/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookResource
 */
export interface WebhookResource {
    /**
     * 
     * @type {string}
     * @memberof WebhookResource
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResource
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookResource
     */
    events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookResource
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof WebhookResource
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the WebhookResource interface.
 */
export function instanceOfWebhookResource(value: object): value is WebhookResource {
    return true;
}

export function WebhookResourceFromJSON(json: any): WebhookResource {
    return WebhookResourceFromJSONTyped(json, false);
}

export function WebhookResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'events': json['events'] == null ? undefined : json['events'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function WebhookResourceToJSON(json: any): WebhookResource {
    return WebhookResourceToJSONTyped(json, false);
}

export function WebhookResourceToJSONTyped(value?: WebhookResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'events': value['events'],
        'active': value['active'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

