/*
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mygrainexchange.mgx.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mygrainexchange.mgx.model.Commodity;
import com.mygrainexchange.mgx.model.MarketPriceRange;
import com.mygrainexchange.mgx.model.Money;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketPrice
 */
public class MarketPriceTest {
    private final MarketPrice model = new MarketPrice();

    /**
     * Model tests for MarketPrice
     */
    @Test
    public void testMarketPrice() {
        // TODO: test MarketPrice
    }

    /**
     * Test the property 'commodity'
     */
    @Test
    public void commodityTest() {
        // TODO: test commodity
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }

    /**
     * Test the property 'changePct'
     */
    @Test
    public void changePctTest() {
        // TODO: test changePct
    }

    /**
     * Test the property 'range'
     */
    @Test
    public void rangeTest() {
        // TODO: test range
    }

    /**
     * Test the property 'asOf'
     */
    @Test
    public void asOfTest() {
        // TODO: test asOf
    }

}
