/*
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mygrainexchange.mgx.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mygrainexchange.mgx.model.PlaceListingQuality;
import com.mygrainexchange.mgx.model.PlaceListingTargetPrice;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlaceListing
 */
public class PlaceListingTest {
    private final PlaceListing model = new PlaceListing();

    /**
     * Model tests for PlaceListing
     */
    @Test
    public void testPlaceListing() {
        // TODO: test PlaceListing
    }

    /**
     * Test the property 'commodity'
     */
    @Test
    public void commodityTest() {
        // TODO: test commodity
    }

    /**
     * Test the property 'farmId'
     */
    @Test
    public void farmIdTest() {
        // TODO: test farmId
    }

    /**
     * Test the property 'quantityMt'
     */
    @Test
    public void quantityMtTest() {
        // TODO: test quantityMt
    }

    /**
     * Test the property 'variety'
     */
    @Test
    public void varietyTest() {
        // TODO: test variety
    }

    /**
     * Test the property 'cropYear'
     */
    @Test
    public void cropYearTest() {
        // TODO: test cropYear
    }

    /**
     * Test the property 'grade'
     */
    @Test
    public void gradeTest() {
        // TODO: test grade
    }

    /**
     * Test the property 'targetPrice'
     */
    @Test
    public void targetPriceTest() {
        // TODO: test targetPrice
    }

    /**
     * Test the property 'isOrganic'
     */
    @Test
    public void isOrganicTest() {
        // TODO: test isOrganic
    }

    /**
     * Test the property 'quality'
     */
    @Test
    public void qualityTest() {
        // TODO: test quality
    }

    /**
     * Test the property 'sellerNotes'
     */
    @Test
    public void sellerNotesTest() {
        // TODO: test sellerNotes
    }

    /**
     * Test the property '_list'
     */
    @Test
    public void _listTest() {
        // TODO: test _list
    }

}
