/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using MyGrainExchange.Api.Client;
using MyGrainExchange.Api.Api;
// uncomment below to import models
//using MyGrainExchange.Api.Model;

namespace MyGrainExchange.Api.Test.Api
{
    /// <summary>
    ///  Class for testing MarketApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MarketApiTests : IDisposable
    {
        private MarketApi instance;

        public MarketApiTests()
        {
            instance = new MarketApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarketApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MarketApi
            //Assert.IsType<MarketApi>(instance);
        }

        /// <summary>
        /// Test MarketCommodities
        /// </summary>
        [Fact]
        public void MarketCommoditiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.MarketCommodities();
            //Assert.IsType<MarketCommodityList>(response);
        }

        /// <summary>
        /// Test MarketHistory
        /// </summary>
        [Fact]
        public void MarketHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string commodity = null;
            //DateOnly? from = null;
            //DateOnly? to = null;
            //string? interval = null;
            //var response = instance.MarketHistory(commodity, from, to, interval);
            //Assert.IsType<PriceHistory>(response);
        }

        /// <summary>
        /// Test MarketPrices
        /// </summary>
        [Fact]
        public void MarketPricesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? commodity = null;
            //DateOnly? date = null;
            //var response = instance.MarketPrices(commodity, date);
            //Assert.IsType<MarketPriceList>(response);
        }
    }
}
