/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using MyGrainExchange.Api.Client;
using MyGrainExchange.Api.Api;
// uncomment below to import models
//using MyGrainExchange.Api.Model;

namespace MyGrainExchange.Api.Test.Api
{
    /// <summary>
    ///  Class for testing TeamsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TeamsApiTests : IDisposable
    {
        private TeamsApi instance;

        public TeamsApiTests()
        {
            instance = new TeamsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TeamsApi
            //Assert.IsType<TeamsApi>(instance);
        }

        /// <summary>
        /// Test TeamGet
        /// </summary>
        [Fact]
        public void TeamGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.TeamGet(id);
            //Assert.IsType<TeamEnvelope>(response);
        }

        /// <summary>
        /// Test TeamList
        /// </summary>
        [Fact]
        public void TeamListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.TeamList();
            //Assert.IsType<TeamList>(response);
        }
    }
}
