/* tslint:disable */
/* eslint-disable */
/**
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team\'s trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Deleted,
  Webhook,
  WebhookCreatedEnvelope,
  WebhookDeliveryPage,
  WebhookList,
} from '../models/index';
import {
    DeletedFromJSON,
    DeletedToJSON,
    WebhookFromJSON,
    WebhookToJSON,
    WebhookCreatedEnvelopeFromJSON,
    WebhookCreatedEnvelopeToJSON,
    WebhookDeliveryPageFromJSON,
    WebhookDeliveryPageToJSON,
    WebhookListFromJSON,
    WebhookListToJSON,
} from '../models/index';

export interface WebhookCreateRequest {
    webhook: Webhook;
}

export interface WebhookDeleteRequest {
    id: string;
}

export interface WebhookDeliveriesRequest {
    id: string;
    limit?: number;
    offset?: number;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * Creates a subscription. The signing secret is returned once in the response and never again.
     * @summary Register a webhook subscription
     * @param {Webhook} webhook 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhookCreateRaw(requestParameters: WebhookCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookCreatedEnvelope>>;

    /**
     * Creates a subscription. The signing secret is returned once in the response and never again.
     * Register a webhook subscription
     */
    webhookCreate(requestParameters: WebhookCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookCreatedEnvelope>;

    /**
     * 
     * @summary Delete a webhook subscription
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhookDeleteRaw(requestParameters: WebhookDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deleted>>;

    /**
     * Delete a webhook subscription
     */
    webhookDelete(requestParameters: WebhookDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deleted>;

    /**
     * 
     * @summary Recent delivery attempts (debugging)
     * @param {string} id 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhookDeliveriesRaw(requestParameters: WebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryPage>>;

    /**
     * Recent delivery attempts (debugging)
     */
    webhookDeliveries(requestParameters: WebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryPage>;

    /**
     * 
     * @summary List webhook subscriptions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    webhookListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookList>>;

    /**
     * List webhook subscriptions
     */
    webhookList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookList>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Creates a subscription. The signing secret is returned once in the response and never again.
     * Register a webhook subscription
     */
    async webhookCreateRaw(requestParameters: WebhookCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookCreatedEnvelope>> {
        if (requestParameters['webhook'] == null) {
            throw new runtime.RequiredError(
                'webhook',
                'Required parameter "webhook" was null or undefined when calling webhookCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["webhooks.write"]);
        }


        let urlPath = `/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookToJSON(requestParameters['webhook']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookCreatedEnvelopeFromJSON(jsonValue));
    }

    /**
     * Creates a subscription. The signing secret is returned once in the response and never again.
     * Register a webhook subscription
     */
    async webhookCreate(requestParameters: WebhookCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookCreatedEnvelope> {
        const response = await this.webhookCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a webhook subscription
     */
    async webhookDeleteRaw(requestParameters: WebhookDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deleted>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhookDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["webhooks.write"]);
        }


        let urlPath = `/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletedFromJSON(jsonValue));
    }

    /**
     * Delete a webhook subscription
     */
    async webhookDelete(requestParameters: WebhookDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deleted> {
        const response = await this.webhookDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Recent delivery attempts (debugging)
     */
    async webhookDeliveriesRaw(requestParameters: WebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhookDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["webhooks.read"]);
        }


        let urlPath = `/webhooks/{id}/deliveries`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryPageFromJSON(jsonValue));
    }

    /**
     * Recent delivery attempts (debugging)
     */
    async webhookDeliveries(requestParameters: WebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryPage> {
        const response = await this.webhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List webhook subscriptions
     */
    async webhookListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookList>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", []);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["webhooks.read"]);
        }


        let urlPath = `/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookListFromJSON(jsonValue));
    }

    /**
     * List webhook subscriptions
     */
    async webhookList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookList> {
        const response = await this.webhookListRaw(initOverrides);
        return await response.value();
    }

}
