/*
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MyGrainExchange.Api.Client.FileParameter;
using OpenAPIDateConverter = MyGrainExchange.Api.Client.OpenAPIDateConverter;

namespace MyGrainExchange.Api.Model
{
    /// <summary>
    /// PlaceListingQuality
    /// </summary>
    [DataContract(Name = "PlaceListing_quality")]
    public partial class PlaceListingQuality : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaceListingQuality" /> class.
        /// </summary>
        /// <param name="protein">protein.</param>
        /// <param name="moisture">moisture.</param>
        /// <param name="testWeight">testWeight.</param>
        /// <param name="dockage">dockage.</param>
        /// <param name="fallingNumber">fallingNumber.</param>
        public PlaceListingQuality(decimal protein = default, decimal moisture = default, decimal testWeight = default, decimal dockage = default, int fallingNumber = default)
        {
            this.Protein = protein;
            this.Moisture = moisture;
            this.TestWeight = testWeight;
            this.Dockage = dockage;
            this.FallingNumber = fallingNumber;
        }

        /// <summary>
        /// Gets or Sets Protein
        /// </summary>
        [DataMember(Name = "protein", EmitDefaultValue = false)]
        public decimal Protein { get; set; }

        /// <summary>
        /// Gets or Sets Moisture
        /// </summary>
        [DataMember(Name = "moisture", EmitDefaultValue = false)]
        public decimal Moisture { get; set; }

        /// <summary>
        /// Gets or Sets TestWeight
        /// </summary>
        [DataMember(Name = "test_weight", EmitDefaultValue = false)]
        public decimal TestWeight { get; set; }

        /// <summary>
        /// Gets or Sets Dockage
        /// </summary>
        [DataMember(Name = "dockage", EmitDefaultValue = false)]
        public decimal Dockage { get; set; }

        /// <summary>
        /// Gets or Sets FallingNumber
        /// </summary>
        [DataMember(Name = "falling_number", EmitDefaultValue = false)]
        public int FallingNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlaceListingQuality {\n");
            sb.Append("  Protein: ").Append(Protein).Append("\n");
            sb.Append("  Moisture: ").Append(Moisture).Append("\n");
            sb.Append("  TestWeight: ").Append(TestWeight).Append("\n");
            sb.Append("  Dockage: ").Append(Dockage).Append("\n");
            sb.Append("  FallingNumber: ").Append(FallingNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
