<?php
/**
 * MarketApi
 * PHP version 8.1
 *
 * @category Class
 * @package  MyGrainExchange\Mgx
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MyGrainExchange\Mgx\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use MyGrainExchange\Mgx\ApiException;
use MyGrainExchange\Mgx\Configuration;
use MyGrainExchange\Mgx\FormDataProcessor;
use MyGrainExchange\Mgx\HeaderSelector;
use MyGrainExchange\Mgx\ObjectSerializer;

/**
 * MarketApi Class Doc Comment
 *
 * @category Class
 * @package  MyGrainExchange\Mgx
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MarketApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'marketCommodities' => [
            'application/json',
        ],
        'marketHistory' => [
            'application/json',
        ],
        'marketPrices' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation marketCommodities
     *
     * Commodities with market-price coverage
     *
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketCommodities'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MyGrainExchange\Mgx\Model\MarketCommodityList|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error
     */
    public function marketCommodities($units = null, string $contentType = self::contentTypes['marketCommodities'][0])
    {
        list($response) = $this->marketCommoditiesWithHttpInfo($units, $contentType);
        return $response;
    }

    /**
     * Operation marketCommoditiesWithHttpInfo
     *
     * Commodities with market-price coverage
     *
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketCommodities'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MyGrainExchange\Mgx\Model\MarketCommodityList|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function marketCommoditiesWithHttpInfo($units = null, string $contentType = self::contentTypes['marketCommodities'][0])
    {
        $request = $this->marketCommoditiesRequest($units, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\MarketCommodityList',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MyGrainExchange\Mgx\Model\MarketCommodityList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\MarketCommodityList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation marketCommoditiesAsync
     *
     * Commodities with market-price coverage
     *
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketCommodities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketCommoditiesAsync($units = null, string $contentType = self::contentTypes['marketCommodities'][0])
    {
        return $this->marketCommoditiesAsyncWithHttpInfo($units, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation marketCommoditiesAsyncWithHttpInfo
     *
     * Commodities with market-price coverage
     *
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketCommodities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketCommoditiesAsyncWithHttpInfo($units = null, string $contentType = self::contentTypes['marketCommodities'][0])
    {
        $returnType = '\MyGrainExchange\Mgx\Model\MarketCommodityList';
        $request = $this->marketCommoditiesRequest($units, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'marketCommodities'
     *
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketCommodities'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function marketCommoditiesRequest($units = null, string $contentType = self::contentTypes['marketCommodities'][0])
    {



        $resourcePath = '/market/commodities';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $units,
            'units', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation marketHistory
     *
     * Price history for a commodity
     *
     * @param  string $commodity Commodity slug, e.g. wheat. (required)
     * @param  \DateTime|null $from from (optional)
     * @param  \DateTime|null $to to (optional)
     * @param  string|null $interval interval (optional, default to 'day')
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketHistory'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MyGrainExchange\Mgx\Model\PriceHistory|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error
     */
    public function marketHistory($commodity, $from = null, $to = null, $interval = 'day', $units = null, string $contentType = self::contentTypes['marketHistory'][0])
    {
        list($response) = $this->marketHistoryWithHttpInfo($commodity, $from, $to, $interval, $units, $contentType);
        return $response;
    }

    /**
     * Operation marketHistoryWithHttpInfo
     *
     * Price history for a commodity
     *
     * @param  string $commodity Commodity slug, e.g. wheat. (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $interval (optional, default to 'day')
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketHistory'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MyGrainExchange\Mgx\Model\PriceHistory|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function marketHistoryWithHttpInfo($commodity, $from = null, $to = null, $interval = 'day', $units = null, string $contentType = self::contentTypes['marketHistory'][0])
    {
        $request = $this->marketHistoryRequest($commodity, $from, $to, $interval, $units, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\PriceHistory',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MyGrainExchange\Mgx\Model\PriceHistory',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\PriceHistory',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation marketHistoryAsync
     *
     * Price history for a commodity
     *
     * @param  string $commodity Commodity slug, e.g. wheat. (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $interval (optional, default to 'day')
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketHistoryAsync($commodity, $from = null, $to = null, $interval = 'day', $units = null, string $contentType = self::contentTypes['marketHistory'][0])
    {
        return $this->marketHistoryAsyncWithHttpInfo($commodity, $from, $to, $interval, $units, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation marketHistoryAsyncWithHttpInfo
     *
     * Price history for a commodity
     *
     * @param  string $commodity Commodity slug, e.g. wheat. (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $interval (optional, default to 'day')
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketHistoryAsyncWithHttpInfo($commodity, $from = null, $to = null, $interval = 'day', $units = null, string $contentType = self::contentTypes['marketHistory'][0])
    {
        $returnType = '\MyGrainExchange\Mgx\Model\PriceHistory';
        $request = $this->marketHistoryRequest($commodity, $from, $to, $interval, $units, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'marketHistory'
     *
     * @param  string $commodity Commodity slug, e.g. wheat. (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  string|null $interval (optional, default to 'day')
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketHistory'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function marketHistoryRequest($commodity, $from = null, $to = null, $interval = 'day', $units = null, string $contentType = self::contentTypes['marketHistory'][0])
    {

        // verify the required parameter 'commodity' is set
        if ($commodity === null || (is_array($commodity) && count($commodity) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $commodity when calling marketHistory'
            );
        }






        $resourcePath = '/market/prices/{commodity}/history';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $interval,
            'interval', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $units,
            'units', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($commodity !== null) {
            $resourcePath = str_replace(
                '{' . 'commodity' . '}',
                ObjectSerializer::toPathValue($commodity),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation marketPrices
     *
     * Market prices, current or as-of a date
     *
     * @param  string|null $commodity Commodity slug(s), comma-separated. (optional)
     * @param  \DateTime|null $date Returns the price as-of that date instead of the current price. (optional)
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketPrices'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \MyGrainExchange\Mgx\Model\MarketPriceList|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error
     */
    public function marketPrices($commodity = null, $date = null, $units = null, string $contentType = self::contentTypes['marketPrices'][0])
    {
        list($response) = $this->marketPricesWithHttpInfo($commodity, $date, $units, $contentType);
        return $response;
    }

    /**
     * Operation marketPricesWithHttpInfo
     *
     * Market prices, current or as-of a date
     *
     * @param  string|null $commodity Commodity slug(s), comma-separated. (optional)
     * @param  \DateTime|null $date Returns the price as-of that date instead of the current price. (optional)
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketPrices'] to see the possible values for this operation
     *
     * @throws \MyGrainExchange\Mgx\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \MyGrainExchange\Mgx\Model\MarketPriceList|\MyGrainExchange\Mgx\Model\Error|\MyGrainExchange\Mgx\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function marketPricesWithHttpInfo($commodity = null, $date = null, $units = null, string $contentType = self::contentTypes['marketPrices'][0])
    {
        $request = $this->marketPricesRequest($commodity, $date, $units, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\MarketPriceList',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\MyGrainExchange\Mgx\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\MyGrainExchange\Mgx\Model\MarketPriceList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\MarketPriceList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MyGrainExchange\Mgx\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation marketPricesAsync
     *
     * Market prices, current or as-of a date
     *
     * @param  string|null $commodity Commodity slug(s), comma-separated. (optional)
     * @param  \DateTime|null $date Returns the price as-of that date instead of the current price. (optional)
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketPrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketPricesAsync($commodity = null, $date = null, $units = null, string $contentType = self::contentTypes['marketPrices'][0])
    {
        return $this->marketPricesAsyncWithHttpInfo($commodity, $date, $units, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation marketPricesAsyncWithHttpInfo
     *
     * Market prices, current or as-of a date
     *
     * @param  string|null $commodity Commodity slug(s), comma-separated. (optional)
     * @param  \DateTime|null $date Returns the price as-of that date instead of the current price. (optional)
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketPrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function marketPricesAsyncWithHttpInfo($commodity = null, $date = null, $units = null, string $contentType = self::contentTypes['marketPrices'][0])
    {
        $returnType = '\MyGrainExchange\Mgx\Model\MarketPriceList';
        $request = $this->marketPricesRequest($commodity, $date, $units, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'marketPrices'
     *
     * @param  string|null $commodity Commodity slug(s), comma-separated. (optional)
     * @param  \DateTime|null $date Returns the price as-of that date instead of the current price. (optional)
     * @param  string|null $units Unit for quantity values (and price values on market endpoints): mt (default), t &#x3D; US short ton, bu &#x3D; commodity-specific bushels, lb, kg. Bushel views require a single-commodity context. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['marketPrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function marketPricesRequest($commodity = null, $date = null, $units = null, string $contentType = self::contentTypes['marketPrices'][0])
    {





        $resourcePath = '/market/prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $commodity,
            'commodity', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date,
            'date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $units,
            'units', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
