/*
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mygrainexchange.mgx.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.mygrainexchange.mgx.model.Commodity;
import com.mygrainexchange.mgx.model.Location;
import com.mygrainexchange.mgx.model.Money;
import com.mygrainexchange.mgx.model.Quantity;
import com.mygrainexchange.mgx.model.UpdateCashBidDelivery;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mygrainexchange.mgx.JSON;

/**
 * CashBid
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CashBid {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  @javax.annotation.Nullable
  private String identifier;

  public static final String SERIALIZED_NAME_COMMODITY = "commodity";
  @SerializedName(SERIALIZED_NAME_COMMODITY)
  @javax.annotation.Nullable
  private Commodity commodity;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private Money price;

  public static final String SERIALIZED_NAME_QUANTITY_MT = "quantity_mt";
  @SerializedName(SERIALIZED_NAME_QUANTITY_MT)
  @javax.annotation.Nullable
  private BigDecimal quantityMt;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private Quantity quantity;

  public static final String SERIALIZED_NAME_DELIVERY_LOCATION_ID = "delivery_location_id";
  @SerializedName(SERIALIZED_NAME_DELIVERY_LOCATION_ID)
  @javax.annotation.Nullable
  private Integer deliveryLocationId;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  @javax.annotation.Nullable
  private Location location;

  public static final String SERIALIZED_NAME_DELIVERY = "delivery";
  @SerializedName(SERIALIZED_NAME_DELIVERY)
  @javax.annotation.Nullable
  private UpdateCashBidDelivery delivery;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "is_active";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  @javax.annotation.Nullable
  private Boolean isActive;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private LocalDate expiresAt;

  public CashBid() {
  }

  public CashBid id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CashBid identifier(@javax.annotation.Nullable String identifier) {
    this.identifier = identifier;
    return this;
  }

  /**
   * Get identifier
   * @return identifier
   */
  @javax.annotation.Nullable
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(@javax.annotation.Nullable String identifier) {
    this.identifier = identifier;
  }


  public CashBid commodity(@javax.annotation.Nullable Commodity commodity) {
    this.commodity = commodity;
    return this;
  }

  /**
   * Get commodity
   * @return commodity
   */
  @javax.annotation.Nullable
  public Commodity getCommodity() {
    return commodity;
  }

  public void setCommodity(@javax.annotation.Nullable Commodity commodity) {
    this.commodity = commodity;
  }


  public CashBid price(@javax.annotation.Nullable Money price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  public Money getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable Money price) {
    this.price = price;
  }


  public CashBid quantityMt(@javax.annotation.Nullable BigDecimal quantityMt) {
    this.quantityMt = quantityMt;
    return this;
  }

  /**
   * Get quantityMt
   * @return quantityMt
   */
  @javax.annotation.Nullable
  public BigDecimal getQuantityMt() {
    return quantityMt;
  }

  public void setQuantityMt(@javax.annotation.Nullable BigDecimal quantityMt) {
    this.quantityMt = quantityMt;
  }


  public CashBid quantity(@javax.annotation.Nullable Quantity quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * The same quantity rendered in the &#x60;?units&#x3D;&#x60; unit (defaults to MT). &#x60;quantity_mt&#x60; is always MT.
   * @return quantity
   */
  @javax.annotation.Nullable
  public Quantity getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable Quantity quantity) {
    this.quantity = quantity;
  }


  public CashBid deliveryLocationId(@javax.annotation.Nullable Integer deliveryLocationId) {
    this.deliveryLocationId = deliveryLocationId;
    return this;
  }

  /**
   * Get deliveryLocationId
   * @return deliveryLocationId
   */
  @javax.annotation.Nullable
  public Integer getDeliveryLocationId() {
    return deliveryLocationId;
  }

  public void setDeliveryLocationId(@javax.annotation.Nullable Integer deliveryLocationId) {
    this.deliveryLocationId = deliveryLocationId;
  }


  public CashBid location(@javax.annotation.Nullable Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @javax.annotation.Nullable
  public Location getLocation() {
    return location;
  }

  public void setLocation(@javax.annotation.Nullable Location location) {
    this.location = location;
  }


  public CashBid delivery(@javax.annotation.Nullable UpdateCashBidDelivery delivery) {
    this.delivery = delivery;
    return this;
  }

  /**
   * Get delivery
   * @return delivery
   */
  @javax.annotation.Nullable
  public UpdateCashBidDelivery getDelivery() {
    return delivery;
  }

  public void setDelivery(@javax.annotation.Nullable UpdateCashBidDelivery delivery) {
    this.delivery = delivery;
  }


  public CashBid isActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   */
  @javax.annotation.Nullable
  public Boolean getIsActive() {
    return isActive;
  }

  public void setIsActive(@javax.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
  }


  public CashBid expiresAt(@javax.annotation.Nullable LocalDate expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public LocalDate getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable LocalDate expiresAt) {
    this.expiresAt = expiresAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashBid cashBid = (CashBid) o;
    return Objects.equals(this.id, cashBid.id) &&
        Objects.equals(this.identifier, cashBid.identifier) &&
        Objects.equals(this.commodity, cashBid.commodity) &&
        Objects.equals(this.price, cashBid.price) &&
        Objects.equals(this.quantityMt, cashBid.quantityMt) &&
        Objects.equals(this.quantity, cashBid.quantity) &&
        Objects.equals(this.deliveryLocationId, cashBid.deliveryLocationId) &&
        Objects.equals(this.location, cashBid.location) &&
        Objects.equals(this.delivery, cashBid.delivery) &&
        Objects.equals(this.isActive, cashBid.isActive) &&
        Objects.equals(this.expiresAt, cashBid.expiresAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, identifier, commodity, price, quantityMt, quantity, deliveryLocationId, location, delivery, isActive, expiresAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashBid {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    commodity: ").append(toIndentedString(commodity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    quantityMt: ").append(toIndentedString(quantityMt)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    deliveryLocationId: ").append(toIndentedString(deliveryLocationId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "identifier", "commodity", "price", "quantity_mt", "quantity", "delivery_location_id", "location", "delivery", "is_active", "expires_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CashBid
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CashBid.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CashBid is not found in the empty JSON string", CashBid.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CashBid.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CashBid` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("identifier") != null && !jsonObj.get("identifier").isJsonNull()) && !jsonObj.get("identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identifier").toString()));
      }
      // validate the optional field `commodity`
      if (jsonObj.get("commodity") != null && !jsonObj.get("commodity").isJsonNull()) {
        Commodity.validateJsonElement(jsonObj.get("commodity"));
      }
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("price"));
      }
      // validate the optional field `quantity`
      if (jsonObj.get("quantity") != null && !jsonObj.get("quantity").isJsonNull()) {
        Quantity.validateJsonElement(jsonObj.get("quantity"));
      }
      // validate the optional field `location`
      if (jsonObj.get("location") != null && !jsonObj.get("location").isJsonNull()) {
        Location.validateJsonElement(jsonObj.get("location"));
      }
      // validate the optional field `delivery`
      if (jsonObj.get("delivery") != null && !jsonObj.get("delivery").isJsonNull()) {
        UpdateCashBidDelivery.validateJsonElement(jsonObj.get("delivery"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CashBid.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CashBid' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CashBid> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CashBid.class));

       return (TypeAdapter<T>) new TypeAdapter<CashBid>() {
           @Override
           public void write(JsonWriter out, CashBid value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CashBid read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CashBid given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CashBid
   * @throws IOException if the JSON string is invalid with respect to CashBid
   */
  public static CashBid fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CashBid.class);
  }

  /**
   * Convert an instance of CashBid to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

