/*
 * MGX Enterprise API
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mygrainexchange.mgx.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.mygrainexchange.mgx.JSON;

/**
 * RequestAnalysis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RequestAnalysis {
  public static final String SERIALIZED_NAME_ANALYSIS_TYPES = "analysis_types";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_TYPES)
  @javax.annotation.Nonnull
  private List<Integer> analysisTypes = new ArrayList<>();

  public RequestAnalysis() {
  }

  public RequestAnalysis analysisTypes(@javax.annotation.Nonnull List<Integer> analysisTypes) {
    this.analysisTypes = analysisTypes;
    return this;
  }

  public RequestAnalysis addAnalysisTypesItem(Integer analysisTypesItem) {
    if (this.analysisTypes == null) {
      this.analysisTypes = new ArrayList<>();
    }
    this.analysisTypes.add(analysisTypesItem);
    return this;
  }

  /**
   * IDs of the analysis offerings to run, from GET /analysis-types.
   * @return analysisTypes
   */
  @javax.annotation.Nonnull
  public List<Integer> getAnalysisTypes() {
    return analysisTypes;
  }

  public void setAnalysisTypes(@javax.annotation.Nonnull List<Integer> analysisTypes) {
    this.analysisTypes = analysisTypes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestAnalysis requestAnalysis = (RequestAnalysis) o;
    return Objects.equals(this.analysisTypes, requestAnalysis.analysisTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysisTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestAnalysis {\n");
    sb.append("    analysisTypes: ").append(toIndentedString(analysisTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("analysis_types"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("analysis_types"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RequestAnalysis
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RequestAnalysis.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestAnalysis is not found in the empty JSON string", RequestAnalysis.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RequestAnalysis.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RequestAnalysis` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestAnalysis.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("analysis_types") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("analysis_types").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysis_types` to be an array in the JSON string but got `%s`", jsonObj.get("analysis_types").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestAnalysis.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestAnalysis' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestAnalysis> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestAnalysis.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestAnalysis>() {
           @Override
           public void write(JsonWriter out, RequestAnalysis value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestAnalysis read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RequestAnalysis given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RequestAnalysis
   * @throws IOException if the JSON string is invalid with respect to RequestAnalysis
   */
  public static RequestAnalysis fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestAnalysis.class);
  }

  /**
   * Convert an instance of RequestAnalysis to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

