<?php
/**
 * TeamsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  MyGrainExchange\Mgx
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MGX Enterprise API
 *
 * Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MyGrainExchange\Mgx\Test\Api;

use \MyGrainExchange\Mgx\Configuration;
use \MyGrainExchange\Mgx\ApiException;
use \MyGrainExchange\Mgx\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MyGrainExchange\Mgx
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for teamGet
     *
     * Get one team.
     *
     */
    public function testTeamGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for teamList
     *
     * Teams the user belongs to.
     *
     */
    public function testTeamList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
