# coding: utf-8

"""
    MGX Enterprise API

    Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from mgx.models.commodity import Commodity
from mgx.models.location import Location
from mgx.models.money import Money
from mgx.models.quantity import Quantity
from mgx.models.update_cash_bid_delivery import UpdateCashBidDelivery
from typing import Optional, Set
from typing_extensions import Self

class CashBid(BaseModel):
    """
    CashBid
    """ # noqa: E501
    id: Optional[StrictStr] = None
    identifier: Optional[StrictStr] = None
    commodity: Optional[Commodity] = None
    price: Optional[Money] = None
    quantity_mt: Optional[Union[StrictFloat, StrictInt]] = None
    quantity: Optional[Quantity] = Field(default=None, description="The same quantity rendered in the `?units=` unit (defaults to MT). `quantity_mt` is always MT.")
    delivery_location_id: Optional[StrictInt] = None
    location: Optional[Location] = None
    delivery: Optional[UpdateCashBidDelivery] = None
    is_active: Optional[StrictBool] = None
    expires_at: Optional[date] = None
    __properties: ClassVar[List[str]] = ["id", "identifier", "commodity", "price", "quantity_mt", "quantity", "delivery_location_id", "location", "delivery", "is_active", "expires_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashBid from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of commodity
        if self.commodity:
            _dict['commodity'] = self.commodity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of quantity
        if self.quantity:
            _dict['quantity'] = self.quantity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of delivery
        if self.delivery:
            _dict['delivery'] = self.delivery.to_dict()
        # set to None if commodity (nullable) is None
        # and model_fields_set contains the field
        if self.commodity is None and "commodity" in self.model_fields_set:
            _dict['commodity'] = None

        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['price'] = None

        # set to None if delivery_location_id (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_location_id is None and "delivery_location_id" in self.model_fields_set:
            _dict['delivery_location_id'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashBid from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "identifier": obj.get("identifier"),
            "commodity": Commodity.from_dict(obj["commodity"]) if obj.get("commodity") is not None else None,
            "price": Money.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "quantity_mt": obj.get("quantity_mt"),
            "quantity": Quantity.from_dict(obj["quantity"]) if obj.get("quantity") is not None else None,
            "delivery_location_id": obj.get("delivery_location_id"),
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "delivery": UpdateCashBidDelivery.from_dict(obj["delivery"]) if obj.get("delivery") is not None else None,
            "is_active": obj.get("is_active"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


