# coding: utf-8

"""
    MGX Enterprise API

    Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mgx.models.commodity import Commodity
from mgx.models.price_history_points_inner import PriceHistoryPointsInner
from typing import Optional, Set
from typing_extensions import Self

class PriceHistory(BaseModel):
    """
    PriceHistory
    """ # noqa: E501
    commodity: Optional[Commodity] = None
    interval: Optional[StrictStr] = None
    points: Optional[List[PriceHistoryPointsInner]] = None
    unit: Optional[StrictStr] = Field(default=None, description="Unit the price points are rendered in.")
    currency: Optional[StrictStr] = Field(default=None, description="ISO currency code for the price points.")
    __properties: ClassVar[List[str]] = ["commodity", "interval", "points", "unit", "currency"]

    @field_validator('interval')
    def interval_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['day', 'week']):
            raise ValueError("must be one of enum values ('day', 'week')")
        return value

    @field_validator('unit')
    def unit_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['mt', 't', 'bu', 'lb', 'kg']):
            raise ValueError("must be one of enum values ('mt', 't', 'bu', 'lb', 'kg')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PriceHistory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of commodity
        if self.commodity:
            _dict['commodity'] = self.commodity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in points (list)
        _items = []
        if self.points:
            for _item_points in self.points:
                if _item_points:
                    _items.append(_item_points.to_dict())
            _dict['points'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PriceHistory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commodity": Commodity.from_dict(obj["commodity"]) if obj.get("commodity") is not None else None,
            "interval": obj.get("interval"),
            "points": [PriceHistoryPointsInner.from_dict(_item) for _item in obj["points"]] if obj.get("points") is not None else None,
            "unit": obj.get("unit"),
            "currency": obj.get("currency")
        })
        return _obj


