# coding: utf-8

"""
    MGX Enterprise API

    Public REST API for grain elevators and enterprise buyers. Browse anonymized inventory, place bids, read your team's trades and bids, manage cash bids, subscribe to webhooks, and read market prices. Authenticate with OAuth2 (Login with MGX). Seller identity is never exposed until a trade is paid on both sides.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebhookEventType(str, Enum):
    """
    WebhookEventType
    """

    """
    allowed enum values
    """
    BID_DOT_ACCEPTED = 'bid.accepted'
    BID_DOT_REJECTED = 'bid.rejected'
    BID_DOT_COUNTERED = 'bid.countered'
    TRADE_DOT_CREATED = 'trade.created'
    TRADE_DOT_SETTLED = 'trade.settled'
    CASHBID_DOT_OFFER_RECEIVED = 'cashbid.offer_received'
    INVENTORY_DOT_MATCHED = 'inventory.matched'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEventType from a JSON string"""
        return cls(json.loads(json_str))


